export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const SUBSCRIBE = 'SUBSCRIBE';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const KEEP_UNSUBSCRIPTION = 'KEEP_UNSUBSCRIPTION';

export const FETCH_USERS = 'FETCH_USERS';
export const KEEP_UNSUBSCRIPTION_USERS = 'KEEP_UNSUBSCRIPTION_USERS';
export const UNSUBSCRIBE_USERS = 'UNSUBSCRIBE_USERS';